making the install section more compact and less redundant

diff --git a/dot_zshrc b/dot_zshrc
--- a/dot_zshrc
+++ b/dot_zshrc
@@ -771,191 +771,6 @@ export VAULT_NAMESPACE=eeff/application
 
 #################################################
 
-################### starship ####################
-
-if ! type "starship" > /dev/null; then
-    if type "brew" > /dev/null; then
-        brew install starship
-    else
-        echo "Can't install starship, because homebrew is not installed."
-    fi
-else
-    export STARSHIP_CONFIG="$HOME"/.config/starship/starship.toml
-    eval "$(starship init zsh)"
-fi
-
-#################################################
-
-alias lc='colorls -lA --sd'
-
-################## eza ##########################
-# https://github.com/eza-community/eza?tab=readme-ov-file
-# eza is an ls alternative tool
-
-if ! type "eza" > /dev/null; then
-    if type "brew" > /dev/null; then
-        brew install eza
-    else
-        echo "Can't install eza, because homebrew is not installed."
-    fi
-else
-    alias ls='eza --icons=always'
-    alias ll='eza -1GlTahx -L 1'
-    alias tree='eza --tree'
-fi
-
-#################################################
-
-################## bat ##########################
-# bat is an less alternative tool
-
-if ! type "bat" > /dev/null; then
-    if type "brew" > /dev/null; then
-        brew install bat
-        bat cache --build
-    else
-        echo "Can't install bat, because homebrew is not installed."
-    fi
-else
-    export BAT_THEME="Catppuccin Mocha"
-    alias less='bat --color=always'
-    alias cat='bat --color=always'
-fi
-
-#################################################
-
-############## ripgrep ##########################
-# ripgrep is an grep alternative tool
-
-if ! type "rg" > /dev/null; then
-    if type "brew" > /dev/null; then
-        brew install ripgrep
-    else
-        echo "Can't install ripgrep, because homebrew is not installed."
-    fi
-# else
-#     alias grep='rg'
-fi
-
-################################################
-
-################# fzf ##########################
-# fzf is a fuzzy finder tool.
-
-if ! type "fzf" > /dev/null; then
-    if type "brew" > /dev/null; then
-        brew install fzf
-    else
-        echo "Can't install fzf, because homebrew is not installed."
-    fi
-else
-    eval "$(fzf --zsh)"
-    [ -f "$HOME"/.fzf.zsh ] && source "$HOME"/.fzf.zsh
-    
-    export FZF_DEFAULT_OPTS="
-    --preview-window=right,70% 
-    --multi 
-    --height=50%
-    --min-height=10
-    --border=double
-    --prompt='find >'
-    --info=inline
-    --pointer='→'
-    --marker=''
-    --header='CTRL-c or Esc to quit'
-    --preview '
-     ([[ -f {} ]] && (bat --color=always {} || cat {} )) ||
-     ([[ -d {} ]] && (tree -C {} | less)) || echo {} 2> /dev/null | head -200'
-    
-    "
-    # Use the CLI find to get all files, excluding any filepath
-    # containing the string "git".
-    # export FZF_DEFAULT_COMMAND='find . -type f ! -path "*git*"'
-
-    # Use the CLI fd to respect ignore files (like '.gitignore'),
-    # display hidden files, and exclude the '.git' directory.
-    export FZF_DEFAULT_COMMAND='fd . --hidden'
-
-    # Use the CLI ripgrep to respect ignore files (like '.gitignore'),
-    # display hidden files, and exclude the '.git' directory.
-    # export FZF_DEFAULT_COMMAND='rg --files --hidden --glob "!.git"'
-    op(){
-        nvim $(fzf)
-    }
-fi
-
-################################################
-
-############## Zoxide ##########################
-# Zoxide is a cd alternative tool
-
-if ! type "zoxide" > /dev/null; then
-    if type "brew" > /dev/null; then
-        brew install zoxide
-    else
-        echo "Can't install zoxide, because homebrew is not installed."
-    fi
-else
-    eval "$(zoxide init --cmd cd zsh)"
-fi
-
-################################################
-
-################### powerlevel10k ##############
-# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
-#
-# [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
-#
-# p10k_colors () {
-#
-#     for i in {0..255}; 
-#     do 
-#         print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}; 
-#     done
-# }
-#
-################################################
-
-################### Yazi #######################
-
-# Yazi is a terminal file manager.
-
-if ! type "yazi" > /dev/null; then
-    if type "brew" > /dev/null; then
-        brew install yazi ffmpegthumbnailer unar jq poppler fd ripgrep fzf zoxide  # font-symbols-only-nerd-font
-    else
-        echo "Can't install yazi, because homebrew is not installed."
-    fi
-else
-    function yy() {
-        yazi "$@" --cwd-file="$tmp"
-        local tmp="$(mktemp -t "yazi-cwd")"
-        if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
-            cd -- "$cwd"
-        fi
-        rm -f -- "$tmp"
-    }
-fi
-
-################################################
-
-################### Atuin ######################
-# Install: curl --proto '=https' --tlsv1.2 -LsSf https://setup.atuin.sh | sh
-if [[ -e "$HOME/.atium/bin/env" ]]; then
-    source "$HOME/.atuin/bin/env"
-fi
-
-if ! type "atuin" > /dev/null; then
-    if type "brew" > /dev/null; then
-        brew install atuin
-    else
-        echo "Can't install atuin, because homebrew is not installed."
-    fi
-else
-    eval "$(atuin init zsh)"
-fi
-################################################
-
 ################### Cheat.sh ###################
 # Installation instructions: 
 #
@@ -995,4 +810,167 @@ set -o vi
 
 # orca aliases 
 [[ -r ~/.orca_profile ]] && source ~/.orca_profile
+
+################################################
+
+
+############## Install apps ####################
+
+# doing this because the cmd is rg and not ripgrep
+if type "rg" > /dev/null; then
+    alias ripgrep="rg"
+fi
+
+export DEFAULT_APP_LIST=( 
+    "atuin" 
+    "bat" 
+    "cargo" 
+    "direnv" 
+    "eza" 
+    "fzf" 
+    "htop" 
+    "ripgrep" 
+    "starship" 
+    "yazi" 
+    "zoxide" 
+) 
+
+# for an_app in $DEFAULT_APP_LIST
+# do
+#     echo "$an_app"
+# done
+
+function atuin_load() {
+    if [[ -e "$HOME/.atium/bin/env" ]]; then
+        source "$HOME/.atuin/bin/env"
+    fi
+    eval "$(atuin init zsh)"
+}
+
+function bat_load() {
+    export BAT_THEME="Catppuccin Mocha"
+    alias less='bat --color=always'
+    alias cat='bat --color=always'
+}
+
+function cargo_load() {
+    export PATH="$HOME/.cargo/bin:$PATH"
+}
+
+function direnv_load() {
+    eval "$(direnv hook zsh)"
+}
+
+function eza_load() {
+    alias ls='eza --icons=always'
+    alias ll='eza -1GlTahx -L 1'
+    alias tree='eza --tree'
+}
+
+function fzf_load() {
+    eval "$(fzf --zsh)"
+    [ -f "$HOME"/.fzf.zsh ] && source "$HOME"/.fzf.zsh
+    
+    # --min-height=20
+    # --multi 
+    export FZF_DEFAULT_OPTS="
+    --preview-window=right,70% 
+    --height=50%
+    --border=double
+    --prompt='find >'
+    --info=inline
+    --pointer='→'
+    --marker=''
+    --header='CTRL-c or Esc to quit'
+    --preview '
+     ([[ -f {} ]] && (bat --color=always {} || cat {} )) ||
+     ([[ -d {} ]] && (tree -C {} | less)) || echo {} 2> /dev/null | head -200'
+    "
+    # Use the CLI find to get all files, excluding any filepath
+    # containing the string "git".
+    # export FZF_DEFAULT_COMMAND='find . -type f ! -path "*git*"'
+
+    # Use the CLI fd to respect ignore files (like '.gitignore'),
+    # display hidden files, and exclude the '.git' directory.
+    export FZF_DEFAULT_COMMAND='fd . --hidden'
+
+    # Use the CLI ripgrep to respect ignore files (like '.gitignore'),
+    # display hidden files, and exclude the '.git' directory.
+    # export FZF_DEFAULT_COMMAND='rg --files --hidden --glob "!.git"'
+    op(){
+        nvim $(fzf)
+    }
+}
+
+function htop_load() {
+
+}
+
+function ripgrep_load () {
+
+}
+
+function starship_load() {
+    export STARSHIP_CONFIG="$HOME"/.config/starship/starship.toml
+    eval "$(starship init zsh)"
+}
+
+function yazi_load(){
+
+    function yy() {
+        yazi "$@" --cwd-file="$tmp"
+        local tmp="$(mktemp -t "yazi-cwd")"
+        if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
+            cd -- "$cwd"
+        fi
+        rm -f -- "$tmp"
+    }
+}
+
+function zoxide_load(){
+    eval "$(zoxide init --cmd cd zsh)"
+}
+
+function brew_install_apps() {
+    echo "\$#: $#" 
+    echo "\$@: $@" 
+    echo "Attempting to install apps via brew..."
+    if [ "$#" -eq 0 ]; then
+        echo "No list of apps were provided."
+        APP=$APP_LIST
+        APP=("${APP_LIST[@]}")
+    else
+        echo "Using default list. "
+        APP=("${@[@]}")
+    fi
+
+    echo "APP is $APP"
+
+    for app in $APP;
+    do 
+        echo "Checking $app"
+        if ! type "$app" > /dev/null; then
+            echo "$app is not installed yet on this system."
+            echo "Attempting to install $app..."
+            if type "brew" > /dev/null; then
+                echo "Installing $app with brew."
+                brew install "$app"
+                load_cmd="$app"_load
+                # echo "Load config $load_cmd."
+                "$load_cmd"
+            else
+                echo "Can't install $app, because homebrew is not installed."
+            fi
+        else
+            echo "$app is already installed"
+            load_cmd="$app"_load
+            # echo "Load config $load_cmd."
+            "$load_cmd"
+        fi
+    done
+    echo "Done with installing brew apps."
+}
+
+brew_install_apps
+################################################
 
